"""empty message

Revision ID: 48c157e70c19
Revises: None
Create Date: 2016-08-10 05:48:13.227844

"""

# revision identifiers, used by Alembic.
revision = '48c157e70c19'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chbible',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bbid', sa.String(), nullable=True),
    sa.Column('snt', sa.String(), nullable=True),
    sa.Column('snt_lg', postgresql.JSON(), nullable=True),
    sa.Column('snt_sdg', postgresql.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chbible')
    ### end Alembic commands ###
